### ISSUE TITLE
rename master branch

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-imp-guide#1]
# Summary
We should rename the branch `master` to `main` and use that going forward for our work.

From [Problematic Terminology in Open-Source](https://blog.carbonfive.com/2018/10/08/problematic-terminology-in-open-source/) on master/slave terminology in software:

> Use of this term is problematic. It references slavery to convey meaning about the relationship between two entities.

Removing this terminology from our workflow is a small gesture to include more people from marginalized groups in this project.

(I’m open to names other than `main`)

## Technical Steps

- [ ]  create main branch from master
- [ ]  make main the default GitHub branch
- [ ]  modify github/central to use main for release notes reloading
- [ ]  redirect PRs to main in w3c/did-imp-guide
- [ ]  move branch protections from master to main
- [ ]  modify docs to reference main instead of master
- [ ]  delete master branch to avoid confusion?

Feedback?

**Comment by selfissued** [comment]
Please no.  This wouldn't just affect the primary repository.  This would affect every branch, every fork, and every local clone, requiring manual steps by all participants to make parallel changes to these copies.  The chances of everyone getting this right are close to zero.

Using git correctly is already complicated enough.  Please don't make this repository even more complicated than usual.

**Comment by iherman** [comment]
Done on 2021-03-25
